/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum170625;

/**
 *
 * @author USer
 */
public class MenuMinuman extends javax.swing.JFrame {

    /**
     * Creates new form MenuMinuman
     */
    
    private MenuUtama utama;
    
    public MenuMinuman() {
        initComponents();
    }
    
    public MenuMinuman(MenuUtama Utama)
    {
        this.utama = Utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbEsTeh = new javax.swing.JComboBox<>();
        totalEsTeh = new javax.swing.JTextField();
        totalPopIce = new javax.swing.JTextField();
        totalEsJeruk = new javax.swing.JTextField();
        totalEsTeler = new javax.swing.JTextField();
        cbPopIce = new javax.swing.JComboBox<>();
        cbEsJeruk = new javax.swing.JComboBox<>();
        cbEsTeler = new javax.swing.JComboBox<>();
        btnTotalMinuman = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        chkEsTeh = new javax.swing.JCheckBox();
        chkPopIce = new javax.swing.JCheckBox();
        chkEsJeruk = new javax.swing.JCheckBox();
        chkEsTeler = new javax.swing.JCheckBox();
        txtEsTeh = new javax.swing.JTextField();
        txtPopIce = new javax.swing.JTextField();
        txtEsJeruk = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        txtEsTeler = new javax.swing.JTextField();
        totalMinuman = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbEsTeh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEsTehActionPerformed(evt);
            }
        });

        totalEsTeh.setText("0");
        totalEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalEsTehActionPerformed(evt);
            }
        });

        totalPopIce.setText("0");

        totalEsJeruk.setText("0");
        totalEsJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalEsJerukActionPerformed(evt);
            }
        });

        totalEsTeler.setText("0");

        cbPopIce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbPopIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPopIceActionPerformed(evt);
            }
        });

        cbEsJeruk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbEsJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEsJerukActionPerformed(evt);
            }
        });

        cbEsTeler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbEsTeler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEsTelerActionPerformed(evt);
            }
        });

        btnTotalMinuman.setText("Total");
        btnTotalMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalMinumanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MENU MINUMAN");

        chkEsTeh.setText("Es Teh");
        chkEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsTehActionPerformed(evt);
            }
        });

        chkPopIce.setText("Pop Ice");
        chkPopIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPopIceActionPerformed(evt);
            }
        });

        chkEsJeruk.setText("Es Jeruk");
        chkEsJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsJerukActionPerformed(evt);
            }
        });

        chkEsTeler.setText("Es Teler");
        chkEsTeler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsTelerActionPerformed(evt);
            }
        });

        txtEsTeh.setText(" ");
        txtEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEsTehActionPerformed(evt);
            }
        });

        txtPopIce.setText(" ");

        txtEsJeruk.setText(" ");

        btnKembali.setText("Kembali ke Menu Utama");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        txtEsTeler.setText(" ");

        totalMinuman.setText(" ");
        totalMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalMinumanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkEsTeh)
                                    .addComponent(chkPopIce)
                                    .addComponent(chkEsJeruk)
                                    .addComponent(chkEsTeler))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPopIce, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEsTeler, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnKembali))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnTotalMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbEsTeler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalEsTeler, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbPopIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalPopIce, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(totalEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEsTeh)
                    .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPopIce)
                    .addComponent(txtPopIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPopIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPopIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEsJeruk)
                    .addComponent(txtEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEsTeler)
                    .addComponent(txtEsTeler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalEsTeler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEsTeler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotalMinuman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEsTehActionPerformed
        int jml = (int)cbEsTeh.getSelectedIndex();
        double harga = Double.parseDouble(txtEsTeh.getText());
        double total = jml*harga;
        totalEsTeh.setText(Double.toString(total));
    }//GEN-LAST:event_cbEsTehActionPerformed

    private void totalEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalEsTehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalEsTehActionPerformed

    private void totalEsJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalEsJerukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalEsJerukActionPerformed

    private void cbPopIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPopIceActionPerformed
        int jml = (int)cbPopIce.getSelectedIndex();
        double harga = Double.parseDouble(txtPopIce.getText());
        double total = jml*harga;
        totalPopIce.setText(Double.toString(total));
    }//GEN-LAST:event_cbPopIceActionPerformed

    private void cbEsJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEsJerukActionPerformed
        int jml = (int)cbEsJeruk.getSelectedIndex();
        double harga = Double.parseDouble(txtEsJeruk.getText());
        double total = jml*harga;
        totalEsJeruk.setText(Double.toString(total));
    }//GEN-LAST:event_cbEsJerukActionPerformed

    private void cbEsTelerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEsTelerActionPerformed
        int jml = (int)cbEsTeler.getSelectedIndex();
        double harga = Double.parseDouble(txtEsTeler.getText());
        double total = jml*harga;
        totalEsTeler.setText(Double.toString(total));
    }//GEN-LAST:event_cbEsTelerActionPerformed

    private void btnTotalMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalMinumanActionPerformed
        double nasgor = Double.parseDouble(totalEsTeh.getText());
        double migor = Double.parseDouble(totalPopIce.getText());
        double sate = Double.parseDouble(totalEsJeruk.getText());
        double soto = Double.parseDouble(totalEsTeler.getText());
        double total = nasgor + migor + sate + soto;
        totalMinuman.setText(String.valueOf(total));
    }//GEN-LAST:event_btnTotalMinumanActionPerformed

    private void chkEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsTehActionPerformed
        txtEsTeh.setText("5000");
    }//GEN-LAST:event_chkEsTehActionPerformed

    private void chkPopIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPopIceActionPerformed
        txtPopIce.setText("10000");
    }//GEN-LAST:event_chkPopIceActionPerformed

    private void chkEsJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsJerukActionPerformed
        txtEsJeruk.setText("7000");
    }//GEN-LAST:event_chkEsJerukActionPerformed

    private void chkEsTelerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsTelerActionPerformed
        txtEsTeler.setText("15000");
    }//GEN-LAST:event_chkEsTelerActionPerformed

    private void txtEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEsTehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEsTehActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = totalMinuman.getText();
        utama.setTotalMinuman(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void totalMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalMinumanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalMinumanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotalMinuman;
    private javax.swing.JComboBox<String> cbEsJeruk;
    private javax.swing.JComboBox<String> cbEsTeh;
    private javax.swing.JComboBox<String> cbEsTeler;
    private javax.swing.JComboBox<String> cbPopIce;
    private javax.swing.JCheckBox chkEsJeruk;
    private javax.swing.JCheckBox chkEsTeh;
    private javax.swing.JCheckBox chkEsTeler;
    private javax.swing.JCheckBox chkPopIce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField totalEsJeruk;
    private javax.swing.JTextField totalEsTeh;
    private javax.swing.JTextField totalEsTeler;
    private javax.swing.JTextField totalMinuman;
    private javax.swing.JTextField totalPopIce;
    private javax.swing.JTextField txtEsJeruk;
    private javax.swing.JTextField txtEsTeh;
    private javax.swing.JTextField txtEsTeler;
    private javax.swing.JTextField txtPopIce;
    // End of variables declaration//GEN-END:variables
}
