/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PenggantiLibur;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Pola extends javax.swing.JFrame {

    /**
     * Creates new form Pola
     */
    public Pola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        editBaris = new javax.swing.JTextField();
        editKolom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbPola = new javax.swing.JComboBox<>();
        btnProccess = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("POLA PERULANGAN BERSARANG");

        jLabel2.setText("Masukkan Baris");

        jLabel3.setText("Masukkan Kolom");

        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        editBaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBarisActionPerformed(evt);
            }
        });

        editKolom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editKolomActionPerformed(evt);
            }
        });

        jLabel4.setText("Masukkan Pola");

        cbPola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pola", "Kotak", "Segi tiga siku-siku", "Segi tiga", "Segi tiga terbalik (blank)", "Jajar genjang" }));
        cbPola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPolaActionPerformed(evt);
            }
        });

        btnProccess.setText("Proses");
        btnProccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProccessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(93, 93, 93)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(editBaris)
                                .addComponent(editKolom)
                                .addComponent(cbPola, 0, 100, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProccess))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(editBaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(editKolom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbPola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProccess))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editBarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBarisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBarisActionPerformed

    private void btnProccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProccessActionPerformed
        try {
            int a = Integer.parseInt(editBaris.getText());
            int b = Integer.parseInt(editKolom.getText());
            int pola = (int)cbPola.getSelectedIndex();
            StringBuilder output = new StringBuilder();
            int i, j;

            switch(pola) {
                case 1: {
                    for(i = 0; i < a; i++) {
                        for(j = 0; j < b; j++) {
                            if(i == 0 || i == a - 1 || j == 0 || j == a - 1) {
                                output.append(" * ");
                            }else {
                                output.append("   ");
                            }
                        }
                        output.append("\n");
                    }
                }break;
                case 2: {
                    for(i = 0; i < a; i++) {
                        for(j = b - 1; j >= i; j--) {
                            output.append("   ");
                        }
                        for(j = 0; j <= i; j++) {
                            output.append(" * ");
                        }
                        output.append("\n\n");
                    }
                }break;
                case 3: {
                    for(i = 0; i < a; i++) {
                        for(j = b - 1; j >= i; j--) {
                            output.append("   ");
                        }
                        for(j = 0; j <= i; j++) {
                            output.append(" * ");
                        }
                        for(j = 1; j <= i; j++) {
                            output.append(" * ");
                        }
                        output.append("\n\n");
                    }
                }break;
                case 4: {
                    for(i = 0; i < a; i++) {
                        for(j = 0; j <= i; j++) {
                            output.append(" * ");
                        }
                        for(j = b - 1; j >= i; j--) {
                            output.append("   ");
                        }
                        for(j = b - 1; j >= i; j--) {
                            output.append("   ");
                        }
                        for(j = 0; j <= i; j++) {
                            output.append(" * ");
                        }
                        output.append("\n\n");
                    }
                }break;
                case 5: {
                    for(i = 0; i < a; i++) {
                        for(j = 0; j <= i; j++) {
                            output.append("  ");
                        }
                        for(j = 0; j < b; j++) {
                            output.append("  *  ");
                        }
                        output.append("\n\n");
                    }
                }break;
            }

            textArea.setText(output.toString());
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input berupa angka", "Error", JOptionPane.INFORMATION_MESSAGE);
            editBaris.setText("");
            editKolom.setText("");
            editBaris.requestFocus();
        }catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnProccessActionPerformed

    private void cbPolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPolaActionPerformed

    private void editKolomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editKolomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editKolomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProccess;
    private javax.swing.JComboBox<String> cbPola;
    private javax.swing.JTextField editBaris;
    private javax.swing.JTextField editKolom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
